project3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from hotel import views

urlpatterns = [
    path('hotel/admin/', admin.site.urls),
    path('',views.landing_view,name='landing_page'),
    path('signup/', views.signup, name='signup'),
    path('login/',views.user_login,name='login'),
    path('user/logout/',views.user_logout,name='user_logout'),
    path('administration/user/logout/',views.administration_logout,name='administration_logout'),
    path('administration/user/signup/', views.signup,name='administration_user_signup'),
    path('administration/user/login/', views.user_login,name='administration_user_login'),
    path('user/home/',views.user_home,name='user_home'),
    path('administration/user/home/',views.administraion_user_home,name='admin_user_home'),
    path('available/rooms/',views.room_list,name='available_rooms'),
    path('book-room/<int:room_id>/', views.book_room, name='book_room'),
    path('select-services/<int:booking_id>/', views.select_services, name='select_services'),
    path('credit-card-info/<int:booking_id>/', views.credit_card_info, name='credit_card_info'),
    path('print-receipt/<int:booking_id>/', views.print_receipt, name='print_receipt'),
    path('booking-confirmation/<int:booking_id>/', views.booking_confirmation, name='booking_confirmation'),
    path('add-room/', views.add_room, name='add_room'),
    path('add-service/', views.add_service, name='add_service'),
    path('services/', views.service_list, name='service_list'),
    path('users/',views.users_list,name='users_list'),
    path('bookings/',views.bookins_list,name='users_list'),
    path('user/bookings/',views.user_bookings_list,name='user_bookings'),
    path('user/profile/',views.user_profile,name='user_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/models.py
from django.db import models


from django.contrib.auth.models import AbstractUser
from django.db import models

# Custom User model that extends AbstractUser
class User(AbstractUser):
   first_name = models.CharField(max_length=60,null=True)
   last_name = models.CharField(max_length=60,null=True)
   email = models.CharField(max_length=60,null=True)

# Room
class Room(models.Model):
    ROOM_TYPES = (
        ('SIN', 'Single'),
        ('DBL', 'Double'),
        ('SUI', 'Suite'),
    )
    room_number = models.CharField(max_length=5, unique=True)
    room_type = models.CharField(max_length=3, choices=ROOM_TYPES)
    capacity = models.IntegerField(null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    is_available = models.BooleanField(default=True)
    image = models.ImageField(upload_to='room_images/', null=True,
                              blank=True)  # Assume you have a media directory set up
    description = models.TextField(null=True, blank=True)


# Service
class Service(models.Model):
    service_name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f"{self.service_name} - ${self.price}"


# Booking
class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)
    check_in = models.DateField()
    check_out = models.DateField()
    total_price = models.DecimalField(max_digits=8, decimal_places=2)
    is_active = models.BooleanField(default=True)



# BookingService (Intermediate model for Many-to-Many relationship between Booking and Service)
class BookingService(models.Model):
    booking = models.ForeignKey(Booking, related_name='booking_services', on_delete=models.CASCADE,null=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE,null=True)
    quantity = models.IntegerField(default=1)



# CreditCard (Dummy model for educational purposes only)
class CreditCard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cardholder_name = models.CharField(max_length=100)
    card_type = models.CharField(max_length=50)
    last_four_digits = models.CharField(max_length=4)
    expiration_month = models.IntegerField()
    expiration_year = models.IntegerField()
    billing_address = models.TextField()



# Payment
class Payment(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    credit_card = models.ForeignKey(CreditCard, on_delete=models.SET_NULL, null=True)
    amount_paid = models.DecimalField(max_digits=8, decimal_places=2)
    payment_date = models.DateField(auto_now_add=True)
    payment_method = models.CharField(max_length=50)  # e.g., 'credit_card', 'paypal'
    status = models.CharField(max_length=50)  # e.g., 'pending', 'completed', 'refunded'

hotel/forms.py
# forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from .models import Booking

User = get_user_model()

from django.contrib.auth.forms import AuthenticationForm
class UserSignUpForm(UserCreationForm):
    username = forms.CharField(max_length=10,label="Mobile Number")
    first_name = forms.CharField(max_length=60, required=True)
    last_name = forms.CharField(max_length=60, required=True)
    email = forms.EmailField(max_length=60, required=True)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

    def __init__(self, *args, **kwargs):
        super(UserSignUpForm, self).__init__(*args, **kwargs)
        self.fields['password1'].label = "Password"
        self.fields['password2'].label = "Confirm Password"

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(max_length=10, label="Mobile Number", widget=forms.TextInput(attrs={'placeholder': 'Mobile Number'}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    def __init__(self, request=None, *args, **kwargs):
        super(UserLoginForm, self).__init__(request, *args, **kwargs)

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['check_in', 'check_out']
        widgets = {
            'check_in': forms.DateInput(attrs={'type': 'date'}),
            'check_out': forms.DateInput(attrs={'type': 'date'}),
        }

from .models import BookingService, Service

class ServiceForm(forms.Form):
    services = forms.ModelMultipleChoiceField(
        queryset=Service.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    quantity = forms.IntegerField(min_value=1, initial=0)

from .models import CreditCard

class CreditCardForm(forms.ModelForm):
    class Meta:
        model = CreditCard
        fields = ['cardholder_name', 'card_type', 'last_four_digits', 'expiration_month', 'expiration_year', 'billing_address']
        widgets = {
            'expiration_month': forms.NumberInput(attrs={'placeholder': 'MM', 'class': 'form-control'}),
            'expiration_year': forms.NumberInput(attrs={'placeholder': 'YYYY', 'class': 'form-control'}),
            'last_four_digits': forms.NumberInput(attrs={'placeholder': 'Last 4 digits', 'class': 'form-control'}),
        }

# forms.py

from django import forms
from .models import Room

class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['room_number', 'room_type', 'capacity', 'price', 'is_available', 'image', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
        }

from .models import Service

class AddServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['service_name', 'price']

hotel/views.py
from django.contrib.auth import login
from django.http import HttpResponseForbidden
from django.shortcuts import render,get_object_or_404

# Create your views here.

def landing_view(request):
    return render(request,'landing_page.html')

from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import UserSignUpForm

from django.contrib import messages

def signup(request):
    if request.method == 'POST':
        print(request.path)
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.mobile_number = user.username
            print("form is valid and user is created")
            # You can also log the user in and then redirect
            if "admin" in request.path:
                user.is_superuser = True
                user.is_staff = True
                user.save()
                login(request,user)
                messages.add_message(request,messages.SUCCESS,'Admin account created successfully.')
                return redirect('admin_user_home')
            user.save()
            login(request, user)
            messages.add_message(request,messages.SUCCESS,'Your user account created successfully.')
            return redirect(reverse('user_home'))
    else:
        form = UserSignUpForm()
    return render(request, 'user_signup.html', {'form': form})

from .forms import UserLoginForm

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()  # Get the authenticated user from the form
            login(request, user)    # Pass both the request and user to the login function
            # Redirect to a success page.
            if "admin" in request.path:
                return redirect('admin_user_home')
            return redirect(reverse('user_home'))
    else:
        form = UserLoginForm()

    return render(request, 'login.html', {'form': form})

from django.contrib.auth import logout
def user_logout(request):
    logout(request)
    return redirect('login')

def administration_logout(request):
    logout(request)
    return redirect('administration_user_login')

def administraion_user_home(request):
    print("coming here")
    return render(request,'administraion_user_home.html')

def user_home(request):
    return render(request,'user_home.html')

from .models import Room
def room_list(request):
    # Get query parameters for search, filter, and price range
    query = request.GET.get('q', '')
    room_type = request.GET.get('type', '')
    min_price = request.GET.get('min_price', '')
    max_price = request.GET.get('max_price', '')

    rooms = Room.objects.all()

    if query:
        rooms = rooms.filter(room_number__icontains=query)
    if room_type:
        rooms = rooms.filter(room_type=room_type)
    if min_price:
        rooms = rooms.filter(price__gte=min_price)
    if max_price:
        rooms = rooms.filter(price__lte=max_price)

    context = {
        'rooms': rooms,
        'min_price': min_price,
        'max_price': max_price
    }
    return render(request, 'room_list.html', context)


from .forms import BookingForm


def book_room(request, room_id):
    room = get_object_or_404(Room, pk=room_id)

    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.room = room
            booking.user = request.user
            booking.total_price = room.price  # You might want to calculate this based on days
            booking.save()
            room.is_available = False
            room.save()
            messages.success(request, 'Room Added successfully.')
            return redirect('select_services', booking_id=booking.id)
    else:
        form = BookingForm()

    return render(request, 'book_room.html', {'form': form, 'room': room})

from .forms import ServiceForm

from .models import Booking,BookingService

def select_services(request, booking_id):
    booking = get_object_or_404(Booking, pk=booking_id)
    if request.method == 'POST':
        form = ServiceForm(request.POST)
        if form.is_valid():
            selected_services = form.cleaned_data['services']
            for service in selected_services:
                BookingService.objects.create(
                    booking=booking,
                    service=service,
                    quantity=form.cleaned_data['quantity']
                )
            messages.success(request, 'Services added to your booking.')
            return redirect('booking_confirmation', booking_id=booking.id)  # Redirect to a confirmation page or similar
    else:
        form = ServiceForm()

    return render(request, 'select_services.html', {'form': form, 'booking': booking})


def booking_confirmation(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    booking_services = BookingService.objects.filter(booking=booking)

    # Calculate the total price for the booking including services
    additional_services_cost = sum(service.service.price * service.quantity for service in booking_services)
    total_cost = booking.total_price + additional_services_cost

    context = {
        'booking': booking,
        'booking_services': booking_services,
        'total_cost': total_cost,
    }
    return render(request, 'booking_confirmation.html', context)



from django.utils import timezone
from .forms import CreditCardForm
from .models import Booking, BookingService, Room, CreditCard,Payment

def credit_card_info(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    if not booking.is_active:  # Check if the booking hasn't been processed already
        messages.error(request, "This booking has already been processed.")
        return redirect('booking_detail', booking_id=booking_id)

        # Calculate the total price including any additional services
    additional_services_cost = sum(
            bs.service.price * bs.quantity for bs in BookingService.objects.filter(booking=booking))
    total_cost = booking.total_price + additional_services_cost
    if request.method == 'POST':
        form = CreditCardForm(request.POST)
        if form.is_valid():
            credit_card = form.save(commit=False)
            credit_card.user = request.user
            credit_card.save()

            # Update booking status and room availability
            booking.is_active = True
            booking.room.is_available = False
            booking.save()
            try:

                # If you have a payment model, you can also create a payment record
                Payment.objects.create(booking=booking, amount_paid=total_cost, credit_card=credit_card,
                                       payment_method='credit-card',payment_date=timezone.now(),status='completed')
            except Exception as e:
                print("Exception in creating the payment:", str(e))
                pass
            try:
                send_booking_receipt_email(booking)
            except Exception as e:
                print("Error in sending mail:", str(e))
                pass
            # Redirect to a confirmation page or the user's booking list
            return redirect('user_bookings')
    else:
        form = CreditCardForm()



    context = {
        'form': form,
        'booking': booking,
        'total_cost': total_cost,
    }
    return render(request, 'credit_card_info.html', context)


def user_bookings(request):
    user = request.user
    bookings = Payment.objects.filter(booking__user=user)
    print("bookings",bookings)
    return render(request, 'user_bookings.html', {'bookings': bookings})


# views.py

from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings

def send_booking_receipt_email(booking):
    subject = 'Your Hotel Booking Receipt'
    html_message = render_to_string('email_receipt.html', {'booking': booking})
    plain_message = strip_tags(html_message)
    from_email = settings.DEFAULT_FROM_EMAIL
    to = booking.user.email

    send_mail(subject, plain_message, from_email, [to], html_message=html_message)

def print_receipt(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    # Make sure the user requesting the receipt is the one who made the booking
    if request.user != booking.user:
        return HttpResponseForbidden()
    return render(request, 'print_receipt.html', {'booking': booking})


from .forms import RoomForm

def add_room(request):
    if not request.user.is_staff:
        messages.error(request, "You are not authorized to view this page.")
        return redirect('administration_user_signup')

    if request.method == 'POST':
        form = RoomForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "New room added successfully!")
            return redirect('available_rooms')  # Redirect to the room list or wherever appropriate
    else:
        form = RoomForm()

    return render(request, 'add_room.html', {'form': form})

from .forms import AddServiceForm

def add_service(request):
    if not request.user.is_superuser:  # Assuming only superusers can add services
        messages.error(request, "You are not authorized to perform this action.")
        return redirect('administration_user_signup')

    if request.method == 'POST':
        form = AddServiceForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "New service added successfully!")
            return redirect('service_list')  # Redirect to the service list view
    else:
        form = AddServiceForm()

    return render(request, 'add_service.html', {'form': form})

from .models import Service

hotel/templates/add_room.html
{% extends 'base.html' %}
 {% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Add New Room</h2>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <center>
            <button type="submit" class="btn primary-btn">Add Room</button>
        </center>
        <br><br>

    </form>
</div>
{% endblock %}

hotel/templates/add_service.html
<!-- add_service.html -->

{% extends 'base.html' %}
 {% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Add New Service</h2>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <center>
            <button type="submit" class="btn primary-btn">Add Service</button>
        </center>

    </form>
</div>
{% endblock %}

hotel/templates/administraion_user_home.html
{% extends 'base.html' %}  <!-- Extend from a base template if you have one -->
 {% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-5">
        <h1 class="text-center">Welcome, Admin Dashboard</h1>
        <div class="row mt-4">
            <!-- Manage Bookings -->


            <!-- Manage Rooms -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">View Rooms</h5>
                        <p class="card-text">View rooms from the system.</p>
                        <a href="/available/rooms/" target="_blank" class="btn primary-btn">Go to Rooms</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Add New Rooms</h5>
                        <p class="card-text">Add new room to the hotel.</p>
                        <a href="/add-room/" target="_blank" class="btn primary-btn">Add Room</a>
                    </div>
                </div>
            </div>

            <!-- Manage Services -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Manage Services</h5>
                        <p class="card-text">Manage additional services offered.</p>
                        <a href="/services/" target="_blank" class="btn primary-btn">Go to Services</a>
                    </div>
                </div>
            </div>

            <!-- Manage Users -->
            <div class="col-md-4 mt-5">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Manage Users</h5>
                        <p class="card-text">Manage user accounts across Hotel.</p>
                        <a href="/users/" target="_blank" class="btn primary-btn">Go to Users</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mt-5">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Manage Bookings</h5>
                        <p class="card-text">View and manage all room bookings.</p>
                        <a href="/bookings/" target="_blank" class="btn primary-btn">Go to Bookings</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mt-5">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Sign Out</h5>
                    <p class="card-text">Logout from the your account.</p>

                    <a href="/administration/user/logout/" class="btn primary-btn">Sign out</a>
                </div>
            </div>
        </div>






        </div>
    </div>
{% endblock %}

hotel/templates/booking_confirmation.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card mx-auto" style="max-width: 800px;"> <!-- Centered card with max-width -->
        <div class="card-header">
            Booking Confirmation
        </div>
        <div class="card-body">
            <h5 class="card-title">Thank you for your reservation, {{ booking.customer.user.first_name }}!</h5>
            <p class="card-text">Your booking details are confirmed as follows:</p>

            <div class="mb-3 text-left"> <!-- Text aligned to left -->
                <strong>Room Number:</strong> {{ booking.room.room_number }}
            </div>
            <div class="mb-3 text-left">
                <strong>Room Type:</strong> {{ booking.room.get_room_type_display }}
            </div>
            <div class="mb-3 text-left">
                <strong>Check-in Date:</strong> {{ booking.check_in|date:"F d, Y" }}
            </div>
            <div class="mb-3 text-left">
                <strong>Check-out Date:</strong> {{ booking.check_out|date:"F d, Y" }}
            </div>
            <div class="mb-3 text-left">
                <strong>Room Price:</strong> ${{ booking.total_price }}
            </div>

            {% if booking_services %}
            <h5 class="mt-4 text-left">Additional Services:</h5>
            <ul class="list-group list-group-flush">
                {% for service in booking_services %}
                <li class="list-group-item text-left">
                    {{ service.service.service_name }} - Quantity: {{ service.quantity }}
                    <span class="badge bg-primary rounded-pill float-end">${{ service.service.price }}</span>
                </li>
                {% endfor %}
            </ul>
            {% endif %}

            <div class="mt-4 text-left">
                <h4>Total Cost: ${{ total_cost }}</h4>
            </div>

            <!-- Button to navigate to credit card section -->
            <div class="mt-4 text-left">
                <a href="{% url 'credit_card_info' booking.id %}" class="btn primary-btn">Proceed to Payment</a>

            </div>
        </div>
    </div>
</div>
{% endblock %}

hotel/templates/bookings_list.html
<!-- service_list.html -->

{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Bookings List</h2>
    {% if bookings %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">User</th>
                <th scope="col">Room</th>
                <th scope="col">Check In</th>
              <th scope="col">Check Out</th>
              <th scope="col">Price</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for b in bookings %}
            <tr>
              <td>{{b.counter}}</td>
                 <td>{{b.user}}</td>
                 <td>{{b.room.pk}}</td>
                 <td>{{b.check_in}}</td>
                 <td>{{b.check_out}}</td>
                 <td>{{b.total_price}}</td>
                 <td>{{b.is_active}}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">No bookings available.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="text-center">
        No bookings available in the hotel.
    </p>
    {% endif %}
</div>
{% endblock %}

hotel/templates/credit_card_info.html
<!-- credit_card_info.html -->

{% extends 'base.html' %}
 {% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <h2 class="text-center">Credit Card Information</h2>
<!--    <p>Please enter your credit card information below:</p>-->
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
             <form method="post" action="{% url 'credit_card_info' booking.id %}">
        {% csrf_token %}
        {{ form|crispy }}

        <div class="mb-3">
            <strong>Total Amount:</strong> ${{ total_cost }}
        </div>
    <center>
        <button type="submit" class="btn primary-btn">Proceed to Payment</button>
        <br>
    </center>

    </form>
        </div>
    </div>

</div>
{% endblock %}

hotel/templates/email_receipt.html
<!-- email_receipt.html -->

<p>Dear {{ booking.user.first_name }},</p>

<p>Thank you for choosing our hotel. Here are the details of your booking:</p>

<ul>
    <li>Booking ID: {{ booking.id }}</li>
    <li>Room Number: {{ booking.room.room_number }}</li>
    <li>Room Type: {{ booking.room.get_room_type_display }}</li>
    <li>Check-in Date: {{ booking.check_in }}</li>
    <li>Check-out Date: {{ booking.check_out }}</li>
    <li>Total Price: ${{ total_cost }}</li>
</ul>

<p>If you have any questions about your booking, please contact us.</p>

<p>Best regards,</p>
<p>Your Hotel Team</p>

hotel/templates/login.html
{% extends 'base.html' %}  <!-- Extend from a base template if you have one -->
 {% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-center">
        {% if "admin" in request.path %}
        Administration - Login
        {% else %}
        User - Login
        {% endif %}
    </h2>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            {% if "admin" in request.path %}
             <form method="post" class="mt-3" action="/administration/user/login/">
                 {% else %}
                 <form method="post" class="mt-3" action="/login/">
                 {% endif %}
        {% csrf_token %}
        {{ form|crispy }}
        <center>
            <button type="submit" class="btn primary-btn">Login</button>
        </center>

        <br><br>
    </form>
        </div>
    </div>

</div>
{% endblock %}

hotel/templates/print_receipt.html
<!-- print_receipt.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Receipt - Booking #{{ booking.id }}</title>
    <!-- Include a Bootstrap CSS for printing or a custom print stylesheet -->
    <link rel="stylesheet" href="{% static 'css/print.css' %}" media="print">
    <script>
        window.onload = function() {
            window.print();
        }
    </script>
</head>
<body>
    <div class="container">
        <h1>Hotel Booking Receipt</h1>
        <p>Thank you for choosing our hotel. Here are the details of your booking:</p>

<ul>
    <li>Booking ID: {{ booking.id }}</li>
    <li>Room Number: {{ booking.room.room_number }}</li>
    <li>Room Type: {{ booking.room.get_room_type_display }}</li>
    <li>Check-in Date: {{ booking.check_in }}</li>
    <li>Check-out Date: {{ booking.check_out }}</li>
    <li>Total Price: ${{ total_cost }}</li>
</ul>


    </div>
</body>
</html>

hotel/templates/service_list.html
<!-- service_list.html -->

{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Service List</h2>
    <br>
    {% if services %}
    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Service Name</th>
                <th scope="col">Price</th>

            </tr>
        </thead>
        <tbody>
            {% for service in services %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ service.service_name }}</td>
                <td>${{ service.price }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">No services available.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <center>
        <a class="btn primary-btn" href="/add-service/">Add Service</a>
    </center>

    {% else %}
    <p class="text-center">
        No Service available in hotel.
    </p>
    {% endif %}
</div>
{% endblock %}

hotel/templates/user_bookings.html
<!-- user_bookings.html -->

{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Your Bookings</h2>
    {% if bookings %}
        <div class="list-group">
            {% for booking in bookings %}
                <a href="#" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">Booking #{{ booking.id }}</h5>
                        <small>Booked on {{ booking.booking_date|date:"F d, Y" }}</small>
                    </div>
                    <p class="mb-1">Room {{ booking.room.room_number }} - {{ booking.room.get_room_type_display }}</p>
                    <small>Check-in: {{ booking.check_in|date:"F d, Y" }} | Check-out: {{ booking.check_out|date:"F d, Y" }}</small>
                    <button onclick="window.open('{% url 'print_receipt' booking.id %}');" class="btn btn-secondary btn-sm mt-2">Print Receipt</button>


                </a>
            {% endfor %}
        </div>
    {% else %}
        <p>You have no bookings.</p>
    {% endif %}
</div>
{% endblock %}

hotel/templates/user_profile.html
<!-- service_list.html -->

{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">User Profile</h2>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
              <th scope="col">Mobile Number</th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <th scope="row">{{ request.user.pk }}</th>
                <td>{{ request.user.first_name }}</td>
                <td>${{ request.user.last_name }}</td>
              <td>{{ request.user.email }}</td>
              <td>{{ request.user.username }}</td>

            </tr>
        </tbody>
    </table>
</div>
{% endblock %}